import {
  CANDIDATE_APPLY_COMMANDS,
  CANDIDATE_COMMANDS,
  CONTINUITY_COMMANDS,
  DRAFT_COMMANDS,
  ENTITY_CANON_COMMANDS,
  IDEA_CAPSULE_COMMANDS,
  LONGFORM_AI_COMMANDS,
  NARRATIVE_PLANNING_COMMANDS,
  PROJECT_PLANNING_COMMANDS,
  PROJECT_STRUCTURE_COMMANDS,
  PROJECT_WORKSPACE_COMMANDS,
  RECOVERY_COMMANDS,
  RESEARCH_COMMANDS,
  RHYTHM_COMMANDS,
  SCENE_BEAT_COMMANDS,
  SEARCH_TOOLS_COMMANDS,
  STATE_PROPOSAL_COMMANDS,
  STORY_KNOWLEDGE_COMMANDS,
  TEXT_IO_COMMANDS,
  VALIDATION_COMMANDS,
  VERSION_COMMANDS,
  type CoreProjectOperation,
} from '@worldforge/contracts';

import type { CoreOperationKind } from './ipc-error-semantics.js';

export type ProjectOperationName = CoreProjectOperation['operation'];

export const PROJECT_OPERATION_SEMANTICS = {
  [PROJECT_WORKSPACE_COMMANDS.getActive]: 'query',
  [PROJECT_WORKSPACE_COMMANDS.getContinuation]: 'query',
  [PROJECT_WORKSPACE_COMMANDS.saveContinuation]: 'mutation',
  [PROJECT_WORKSPACE_COMMANDS.create]: 'mutation',
  [PROJECT_WORKSPACE_COMMANDS.openSelected]: 'mutation',
  [PROJECT_WORKSPACE_COMMANDS.openRecent]: 'mutation',
  [PROJECT_WORKSPACE_COMMANDS.close]: 'mutation',
  [PROJECT_WORKSPACE_COMMANDS.move]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.listStructure]: 'query',
  [PROJECT_STRUCTURE_COMMANDS.createVolume]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.updateVolume]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.moveVolume]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.deleteVolume]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.createChapter]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.updateChapter]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.moveChapter]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.deleteChapter]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.listTrash]: 'query',
  [PROJECT_STRUCTURE_COMMANDS.restoreTrashEntry]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.previewPermanentDelete]: 'query',
  [PROJECT_STRUCTURE_COMMANDS.permanentDelete]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.previewSplitChapter]: 'query',
  [PROJECT_STRUCTURE_COMMANDS.splitChapter]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.previewMergeChapters]: 'query',
  [PROJECT_STRUCTURE_COMMANDS.mergeChapters]: 'mutation',
  [PROJECT_STRUCTURE_COMMANDS.previewMoveBlocks]: 'query',
  [PROJECT_STRUCTURE_COMMANDS.moveBlocks]: 'mutation',
  [PROJECT_PLANNING_COMMANDS.getBrief]: 'query',
  [PROJECT_PLANNING_COMMANDS.updateBrief]: 'mutation',
  [PROJECT_PLANNING_COMMANDS.listPlotNodes]: 'query',
  [PROJECT_PLANNING_COMMANDS.createPlotNode]: 'mutation',
  [PROJECT_PLANNING_COMMANDS.updatePlotNode]: 'mutation',
  [PROJECT_PLANNING_COMMANDS.movePlotNode]: 'mutation',
  [PROJECT_PLANNING_COMMANDS.deletePlotNode]: 'mutation',
  [SCENE_BEAT_COMMANDS.listSceneBeats]: 'query',
  [SCENE_BEAT_COMMANDS.createSceneBeat]: 'mutation',
  [SCENE_BEAT_COMMANDS.updateSceneBeat]: 'mutation',
  [SCENE_BEAT_COMMANDS.moveSceneBeat]: 'mutation',
  [SCENE_BEAT_COMMANDS.previewMoveSceneBeat]: 'query',
  [SCENE_BEAT_COMMANDS.moveSceneBeatAcrossChapters]: 'mutation',
  [SCENE_BEAT_COMMANDS.deleteSceneBeat]: 'mutation',
  [SCENE_BEAT_COMMANDS.restoreSceneBeat]: 'mutation',
  [SCENE_BEAT_COMMANDS.setSceneBeatBlockLinks]: 'mutation',
  [SCENE_BEAT_COMMANDS.convertBlocksToSceneBeat]: 'mutation',
  [ENTITY_CANON_COMMANDS.listEntities]: 'query',
  [ENTITY_CANON_COMMANDS.createEntity]: 'mutation',
  [ENTITY_CANON_COMMANDS.updateEntity]: 'mutation',
  [ENTITY_CANON_COMMANDS.archiveEntity]: 'mutation',
  [ENTITY_CANON_COMMANDS.setCanonFact]: 'mutation',
  [ENTITY_CANON_COMMANDS.linkSceneBeatEntity]: 'mutation',
  [ENTITY_CANON_COMMANDS.previewDeleteEntity]: 'query',
  [ENTITY_CANON_COMMANDS.deleteEntity]: 'mutation',
  [CONTINUITY_COMMANDS.list]: 'query',
  [CONTINUITY_COMMANDS.setEntityState]: 'mutation',
  [CONTINUITY_COMMANDS.invalidateEntityState]: 'mutation',
  [CONTINUITY_COMMANDS.saveTimelineEvent]: 'mutation',
  [CONTINUITY_COMMANDS.archiveTimelineEvent]: 'mutation',
  [CONTINUITY_COMMANDS.setKnowledgeState]: 'mutation',
  [CONTINUITY_COMMANDS.invalidateKnowledgeState]: 'mutation',
  [CONTINUITY_COMMANDS.setCharacterRelationship]: 'mutation',
  [CONTINUITY_COMMANDS.invalidateCharacterRelationship]: 'mutation',
  [NARRATIVE_PLANNING_COMMANDS.list]: 'query',
  [NARRATIVE_PLANNING_COMMANDS.saveForeshadowing]: 'mutation',
  [NARRATIVE_PLANNING_COMMANDS.transitionForeshadowing]: 'mutation',
  [NARRATIVE_PLANNING_COMMANDS.saveCharacterArc]: 'mutation',
  [NARRATIVE_PLANNING_COMMANDS.saveArcMilestone]: 'mutation',
  [NARRATIVE_PLANNING_COMMANDS.transitionArcMilestone]: 'mutation',
  [STATE_PROPOSAL_COMMANDS.list]: 'query',
  [STATE_PROPOSAL_COMMANDS.generate]: 'mutation',
  [STATE_PROPOSAL_COMMANDS.resolve]: 'mutation',
  [STATE_PROPOSAL_COMMANDS.refreshSnapshot]: 'mutation',
  [STATE_PROPOSAL_COMMANDS.readSnapshot]: 'query',
  [STATE_PROPOSAL_COMMANDS.invalidateDerived]: 'mutation',
  [VALIDATION_COMMANDS.list]: 'query',
  [VALIDATION_COMMANDS.runRules]: 'mutation',
  [VALIDATION_COMMANDS.updateIssue]: 'mutation',
  [VALIDATION_COMMANDS.createTodoFromIssue]: 'mutation',
  [VALIDATION_COMMANDS.saveTodo]: 'mutation',
  [VALIDATION_COMMANDS.addComment]: 'mutation',
  [VALIDATION_COMMANDS.resolveComment]: 'mutation',
  [VALIDATION_COMMANDS.rememberException]: 'mutation',
  [VALIDATION_COMMANDS.disableException]: 'mutation',
  [SEARCH_TOOLS_COMMANDS.search]: 'query',
  [SEARCH_TOOLS_COMMANDS.getIndexState]: 'query',
  [SEARCH_TOOLS_COMMANDS.rebuildIndex]: 'mutation',
  [SEARCH_TOOLS_COMMANDS.previewReplace]: 'mutation',
  [SEARCH_TOOLS_COMMANDS.applyReplace]: 'mutation',
  [SEARCH_TOOLS_COMMANDS.listDictionary]: 'query',
  [SEARCH_TOOLS_COMMANDS.upsertDictionary]: 'mutation',
  [SEARCH_TOOLS_COMMANDS.deleteDictionary]: 'mutation',
  [RHYTHM_COMMANDS.get]: 'query',
  [RHYTHM_COMMANDS.updateProfile]: 'mutation',
  [RHYTHM_COMMANDS.run]: 'mutation',
  [STORY_KNOWLEDGE_COMMANDS.project]: 'query',
  [LONGFORM_AI_COMMANDS.getSettings]: 'query',
  [LONGFORM_AI_COMMANDS.updateSettings]: 'mutation',
  [LONGFORM_AI_COMMANDS.listDigests]: 'query',
  [LONGFORM_AI_COMMANDS.rebuildDigests]: 'mutation',
  [LONGFORM_AI_COMMANDS.evaluateStyle]: 'query',
  [LONGFORM_AI_COMMANDS.resolveTaskRoute]: 'query',
  [IDEA_CAPSULE_COMMANDS.list]: 'query',
  [IDEA_CAPSULE_COMMANDS.get]: 'query',
  [IDEA_CAPSULE_COMMANDS.create]: 'mutation',
  [IDEA_CAPSULE_COMMANDS.setStatus]: 'mutation',
  [IDEA_CAPSULE_COMMANDS.previewConversion]: 'query',
  [IDEA_CAPSULE_COMMANDS.applyConversion]: 'mutation',
  [RESEARCH_COMMANDS.list]: 'query',
  [RESEARCH_COMMANDS.createNote]: 'mutation',
  [RESEARCH_COMMANDS.updateNote]: 'mutation',
  [RESEARCH_COMMANDS.setNoteStatus]: 'mutation',
  [RESEARCH_COMMANDS.deleteNote]: 'mutation',
  [RESEARCH_COMMANDS.importAttachment]: 'mutation',
  [RESEARCH_COMMANDS.previewAttachment]: 'query',
  [RESEARCH_COMMANDS.deleteAttachment]: 'mutation',
  [RESEARCH_COMMANDS.addLink]: 'mutation',
  [RESEARCH_COMMANDS.removeLink]: 'mutation',
  [DRAFT_COMMANDS.openDraft]: 'query',
  [DRAFT_COMMANDS.applyPatch]: 'mutation',
  [CANDIDATE_COMMANDS.createFixtureCandidate]: 'mutation',
  [CANDIDATE_COMMANDS.listCandidates]: 'query',
  [CANDIDATE_COMMANDS.getCandidate]: 'query',
  [CANDIDATE_COMMANDS.discardCandidate]: 'mutation',
  [CANDIDATE_COMMANDS.editSkeleton]: 'mutation',
  [CANDIDATE_APPLY_COMMANDS.previewCandidate]: 'mutation',
  [CANDIDATE_APPLY_COMMANDS.cancelPreview]: 'mutation',
  [CANDIDATE_APPLY_COMMANDS.applyCandidate]: 'mutation',
  [CANDIDATE_APPLY_COMMANDS.findUndoRecord]: 'query',
  [CANDIDATE_APPLY_COMMANDS.previewUndo]: 'query',
  [CANDIDATE_APPLY_COMMANDS.undoApply]: 'mutation',
  [VERSION_COMMANDS.createVersion]: 'mutation',
  [VERSION_COMMANDS.listVersions]: 'query',
  [VERSION_COMMANDS.getVersion]: 'query',
  [VERSION_COMMANDS.setFinalVersion]: 'mutation',
  [VERSION_COMMANDS.restoreVersion]: 'mutation',
  [RECOVERY_COMMANDS.createCheckpoint]: 'mutation',
  [RECOVERY_COMMANDS.createDailyBackup]: 'mutation',
  [RECOVERY_COMMANDS.createNamedSnapshot]: 'mutation',
  [RECOVERY_COMMANDS.getOverview]: 'query',
  [RECOVERY_COMMANDS.updatePolicy]: 'mutation',
  [RECOVERY_COMMANDS.setProtection]: 'mutation',
  [RECOVERY_COMMANDS.previewCleanup]: 'query',
  [RECOVERY_COMMANDS.applyCleanup]: 'mutation',
  [RECOVERY_COMMANDS.restoreCheckpoint]: 'mutation',
  [RECOVERY_COMMANDS.exportVersion]: 'mutation',
  [TEXT_IO_COMMANDS.previewImport]: 'query',
  [TEXT_IO_COMMANDS.commitImport]: 'mutation',
  [TEXT_IO_COMMANDS.listExportVersions]: 'query',
  [TEXT_IO_COMMANDS.exportVersions]: 'mutation',
} as const satisfies Record<ProjectOperationName, CoreOperationKind>;

export function projectOperationKind(operation: ProjectOperationName): CoreOperationKind {
  return PROJECT_OPERATION_SEMANTICS[operation];
}
