import type {
  AppearancePreferences,
  AppSettings,
  AppSettingsSnapshot,
  AppSettingsUpdate,
  ProjectWorkspaceSummary,
  ProjectStructure,
  Volume,
  Chapter,
  LifecycleStatus,
  TrashEntry,
  RecentProject,
  DraftDocument,
  ProjectBrief,
  PlotNode,
  PlotNodeType,
  SceneBeat,
  SceneBeatType,
} from '@worldforge/contracts';

export type ContentWidthPreference = AppearancePreferences['contentWidth'];

export type {
  AppearancePreferences,
  AppSettings,
  AppSettingsSnapshot,
  AppSettingsUpdate,
  ProjectWorkspaceSummary,
  ProjectStructure,
  Volume,
  Chapter,
  LifecycleStatus,
  TrashEntry,
  RecentProject,
  DraftDocument,
  ProjectBrief,
  PlotNode,
  PlotNodeType,
  SceneBeat,
  SceneBeatType,
};
