import type { CandidateApplyService } from './candidate-apply.js';
import type { CandidateService } from './candidate.js';
import type { ContinuityService } from './continuity.js';
import type { DraftService } from './draft.js';
import type { EntityCanonService } from './entity-canon.js';
import type { IdeaCapsuleService } from './idea-capsule-service.js';
import type { ImportExportService } from './import-export.js';
import type { LongformAiService } from './longform-ai-service.js';
import type { ProjectPlanningService } from './project-planning.js';
import type { ProjectContinuationService } from './project-continuation.js';
import type { ProjectStructureService } from './project-structure.js';
import type { ProjectWorkspaceService } from './project-workspace.js';
import type { RecoveryService } from './recovery.js';
import type { ResearchService } from './research-service.js';
import type { SceneBeatService } from './scene-beat.js';
import type { SearchToolsService } from './search-tools.js';
import type { StoryKnowledgeProjectionService } from './story-knowledge-service.js';
import type { StructureOperationService } from './structure-operations.js';
import type { VersionService } from './version.js';
import type { RhythmService } from './rhythm.js';

export interface UtilityProjectServices {
  readonly projectWorkspace: ProjectWorkspaceService;
  readonly projectContinuation: ProjectContinuationService;
  readonly projectStructure: ProjectStructureService;
  readonly projectPlanning: ProjectPlanningService;
  readonly sceneBeats: SceneBeatService;
  readonly entityCanon: EntityCanonService;
  readonly continuity: ContinuityService;
  readonly storyKnowledge: StoryKnowledgeProjectionService;
  readonly ideas: IdeaCapsuleService;
  readonly longformAi: LongformAiService;
  readonly research: ResearchService;
  readonly structureOperations: StructureOperationService;
  readonly drafts: DraftService;
  readonly candidates: CandidateService;
  readonly candidateApply: CandidateApplyService;
  readonly versions: VersionService;
  readonly recovery: RecoveryService;
  readonly textIo: ImportExportService;
  readonly searchTools: SearchToolsService;
  readonly rhythm: RhythmService;
  readonly checkpointRequestId: (requestId: string) => string;
}
