export const AUTHOR_TERMS = {
  project: '作品',
  workspace: '作品目录',
  draft: '当前稿',
  draftBlock: '正文段落',
  revision: '保存序号',
  version: '历史版本',
  finalVersion: '定稿',
  finalize: '设为定稿',
  restoreVersion: '恢复为新当前稿',
  lock: '锁定正文段落',
  checkpoint: '恢复点',
  namedSnapshot: '命名快照',
  continuation: '继续写作位置',
  provider: 'AI连接',
  providerConfig: 'AI连接配置',
  model: 'AI模型',
  generationRun: 'AI任务',
  prompt: '生成指令',
  promptVersion: '生成指令版本',
  candidate: 'AI建议稿',
  skeletonCandidate: '情节方向',
  proseCandidate: '正文建议稿',
  partialCandidate: '未完成建议稿',
  rewriteCandidate: '改写建议稿',
  mergeCandidate: '融合建议稿',
  candidateApply: '采用AI建议稿',
  candidateDiscard: '放弃AI建议稿',
  candidateUndo: '撤销采用',
  staleSource: '来源已经变化',
  projectBrief: '作品核心',
  plotNode: '大纲节点',
  sceneBeat: '场景',
  canon: '人物与世界',
  canonFact: '已确认事实',
  entityState: '动态状态',
  stateProposal: 'AI设定建议',
  aiReview: 'AI审阅',
  reviewProposal: 'AI审阅建议',
  timelineEvent: '时间线事件',
  knowledgeState: '人物知情状态',
  characterArc: '人物成长线',
  arcMilestone: '成长节点',
  foreshadowing: '伏笔',
  evidence: '内容依据',
  validation: '内容检查',
  validationRule: '检查规则',
  validationIssue: '检查问题',
  severity: '重要程度',
  storyTodo: '修改任务',
  comment: '审阅批注',
  rhythm: '连载节奏',
  hook: '章末悬念',
  goldenThree: '黄金三章',
  excitementDensity: '爽点与转折密度',
  searchIndex: '全文搜索索引',
  fullTextSearch: '全文搜索',
  replacePlan: '替换预览',
  importPlan: '导入预览',
  recovery: '恢复',
  recoveryCenter: '恢复中心',
  backup: '备份',
  readOnlyMode: '只读保护',
  migration: '数据结构升级',
  schemaVersion: '数据结构版本',
  core: '本地服务',
  renderer: '应用界面',
  mainProcess: '桌面主程序',
  preload: '安全连接层',
  bridge: '功能连接层',
  ipc: '程序内部通信',
  statusArbiter: '全局状态提示',
  workspaceAttention: '待处理事项汇总',
  disclosureMode: '信息显示方式',
  beginnerMode: '简明模式',
  professionalMode: '完整模式',
  focusMode: '沉浸写作',
  onboarding: '首次使用引导',
  navigationTarget: '跳转目标',
  dialog: '对话框',
  testEvidence: '验证记录',
  fixture: '测试样本',
  endToEnd: '完整流程测试',
  qualityGate: '质量门禁',
  performanceBudget: '性能上限',
  smokeTest: '启动检查',
} as const;

export type AuthorTermKey = keyof typeof AUTHOR_TERMS;

export function authorTerm(key: AuthorTermKey): (typeof AUTHOR_TERMS)[AuthorTermKey] {
  return AUTHOR_TERMS[key];
}

export interface TechnicalTermDetail {
  readonly authorLabel: string;
  readonly internalName: string;
}

export function technicalTermDetail(key: AuthorTermKey, internalName: string): TechnicalTermDetail {
  return {
    authorLabel: authorTerm(key),
    internalName,
  };
}
